name: Request to add a public Go vulnerability the vulndb database
description: |
  Use this form to report existing, public vulnerabilities in public importable packages 
  in the Go ecosystem. 
title: "x/vulndb: potential Go vuln in <package>"
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: module
    attributes:
      label: Module
      description: The Go module this vulnerability affects.
      placeholder: github.com/example/module
    validations:
      required: true
  - type: input
    id: package
    attributes:
      label: Package
      description: The Go package this vulnerability affects. Leave blank if same as module.
      placeholder: github.com/example/module/package
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A description of the vulnerability.
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Affected Versions
      description: |
        The package versions (in semver format) affected by this vulnerability.
      placeholder: |
        - Introduced: 1.1.0
          Fixed: 1.8.5
      render: markdown
    validations:
      required: true
  - type: textarea
    id: symbols
    attributes:
      label: Affected Symbols
      description: |
        The symbols (function or struct names) affected by this vulnerability.
      placeholder: |
        - AFunction
        - aType.AMethod
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: has-cve
    attributes:
      label: Does this vulnerability already have a CVE ID?
      multiple: false
      options:
      - "Yes"
      - "No"
      - "Unknown"
    validations:
      required: true
  - type: input
    id: cve
    attributes:
      label: CVE ID
      description: The CVE ID for this vulnerability. Leave blank if none exists.
      placeholder: CVE-20XX-NNNN
    validations:
      required: false
 
#  - type: textarea
#    id: symbols
#    attributes:
#      label: Affected Symbols
#      description: |
#        The symbols (function or struct names) affected by this vulnerability.
#      placeholder: |
#        - AFunction
#        - aType.AMethod
#      render: markdown
#   validations:
#     required: true
