name: Request to add a public Go vulnerability the vulndb database
description: |
  Use this form to report existing, public vulnerabilities in public importable packages 
  in the Go ecosystem. 
title: "x/vulndb: potential Go vuln in <package>"
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: module
    attributes:
      label: Module
      description: The Go module this vulnerability affects.
      placeholder: github.com/example/module
    validations:
      required: true
  - type: input
    id: package
    attributes:
      label: Package
      description: The Go package this vulnerability affects. Leave blank if same as module.
      placeholder: github.com/example/module/package
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A description of the vulnerability.
    validations:
      required: true
