name: Request to add a public Go vulnerability the vulndb database
description: |
  Report existing, public vulnerabilities in public importable packages in the Go ecosystem. 
  For all other vulnerabilities, please follow our [security policy](https://go.dev/security).
title: "x/vulndb: potential Go vuln in <package>"
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: module
    attributes:
      label: Module
      description: The Go module this vulnerability affects.
      placeholder: https://github.com/example
    validations:
      required: true
