name: Request to add a public Go vulnerability the vulndb database
description: |
  Use this form to report existing, publicly disclosed vulnerabilities in public importable packages in the external Go ecosystem.

  To report a potential vulnerability in the Go standard library, Go toolchain, or the golang.org modules, please read our [security policy](https://go.dev/security) and email us directly at security@golang.org.
title: "x/vulndb: potential Go vuln in <package>"
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: module
    attributes:
      label: Module
      description: The Go module this vulnerability affects.
      placeholder: https://github.com/example
    validations:
      required: true
